import type { AppData, Role, RoleKey } from "./types"

export const ROLES: Record<RoleKey, Role> = {
  paula: {
    name: "Paula",
    label: "Socia 1",
    pin: "1111",
    full: true,
    partner: "paula",
  },
  cami: {
    name: "Cami",
    label: "Socia 2",
    pin: "2222",
    full: true,
    partner: "cami",
  },
  empleada: {
    name: "Empleada",
    label: "Empleada",
    pin: "0000",
    full: false,
    partner: null,
  },
}

export const canSee = (r: RoleKey | null): boolean => {
  if (!r) return false
  return ROLES[r]?.full ?? false
}

export const partnerKey = (r: RoleKey | null): RoleKey | null => {
  if (!r) return null
  return ROLES[r]?.partner ?? null
}

export const SEED_DATA: AppData = {
  projects: [
    {
      id: "p1",
      name: "Casa Moreno",
      client: "Familia Moreno",
      address: "Bella Vista, Ituzaingo",
      type: "arquitectura",
      status: "activo",
      createdAt: "2026-01-15",
      margin: 1.4,
      honorarios: {
        cost: 800000,
        clientPrice: 1120000,
      },
      manoDeObra: [
        {
          id: "mo1",
          description: "Demolicion y estructura",
          cost: 450000,
          clientPrice: 630000,
          paid: false,
        },
        {
          id: "mo2",
          description: "Pintura interior",
          cost: 180000,
          clientPrice: 252000,
          paid: true,
        },
      ],
      materiales: [
        {
          id: "ma1",
          description: "Hierros y cemento",
          cost: 320000,
          clientPrice: 448000,
          category: "Corralon",
        },
        {
          id: "ma2",
          description: "Ceramicos bano",
          cost: 95000,
          clientPrice: 133000,
          category: "Sanitarios",
        },
      ],
      mobiliario: [],
      movements: [
        {
          id: "v1",
          date: "2026-01-20",
          description: "Sena 50% honorarios",
          amount: 560000,
          type: "ingreso",
          category: "Honorarios",
          providerId: null,
        },
        {
          id: "v2",
          date: "2026-02-05",
          description: "Pago Carpinteria Lopez",
          amount: 95000,
          type: "egreso",
          category: "Mano de obra",
          providerId: "pr3",
        },
        {
          id: "v3",
          date: "2026-02-18",
          description: "Anticipo corralon",
          amount: 160000,
          type: "egreso",
          category: "Materiales",
          providerId: "pr1",
        },
      ],
      files: [
        {
          id: "f1",
          name: "Contrato_Moreno.pdf",
          category: "contrato",
          date: "2026-01-15",
          url: "#",
        },
      ],
      quotes: [],
    },
    {
      id: "p2",
      name: "Depto Vidal",
      client: "Sra. Vidal",
      address: "Recoleta, CABA",
      type: "interiorismo",
      status: "activo",
      createdAt: "2026-02-01",
      margin: 1.5,
      honorarios: {
        cost: 400000,
        clientPrice: 600000,
      },
      manoDeObra: [],
      materiales: [],
      mobiliario: [],
      movements: [],
      files: [],
      quotes: [
        {
          id: "q2",
          item: "Sillon living",
          margin: 1.6,
          selectedIndex: 1,
          options: [
            { providerName: "Muebles Palermo", amount: 420000 },
            { providerName: "Fabrica Oeste", amount: 240000 },
            { providerName: "Importadora Sur", amount: 310000 },
          ],
        },
      ],
    },
  ],
  providers: [
    {
      id: "pr1",
      name: "Corralon San Martin",
      category: "Construcción",
      subcategory: "Corralones",
      zone: "Zona Oeste",
      phone: "011-4521-1234",
      email: "info@corralonsanmartin.com",
      contact: "Carlos López",
      advancePercent: 50,
      notes: "Proveedor confiable, entregas rápidas",
      payments: [
        {
          id: "pp1",
          date: "2026-02-18",
          projectId: "p1",
          projectName: "Casa Moreno",
          budgetAmount: 320000,
          advancePercentage: 50,
          advanceAmount: 160000,
          balanceAmount: 160000,
          status: "anticipo-pagado",
          description: "Anticipo materiales",
          amount: 160000,
        },
      ],
      quoteHistory: [
        {
          id: "qh1",
          date: "2026-02-15",
          projectId: "p1",
          projectName: "Casa Moreno",
          category: "Materiales",
          item: "Hierros y cemento",
          costProvider: 320000,
          priceClient: 448000,
          ganancia: 128000,
        },
      ],
      documents: [],
      projectIds: ["p1"],
    },
    {
      id: "pr2",
      name: "Sanitarios Belgrano",
      category: "Sanitarios",
      subcategory: "Griferías",
      zone: "Recoleta",
      phone: "011-4789-5678",
      email: "ventas@sanitariosbel.com",
      contact: "María Perez",
      advancePercent: 60,
      notes: "Piden 60% para comenzar",
      payments: [],
      quoteHistory: [],
      documents: [],
      projectIds: [],
    },
    {
      id: "pr3",
      name: "Carpinteria Lopez",
      category: "Mobiliario",
      subcategory: "Carpintería",
      zone: "Zona Oeste",
      phone: "011-4322-9876",
      email: "lopez@carpinteria.com",
      contact: "Jorge Lopez",
      advancePercent: 50,
      notes: "Excelente calidad, trabajos a medida",
      payments: [
        {
          id: "pp2",
          date: "2026-02-05",
          projectId: "p1",
          projectName: "Casa Moreno",
          budgetAmount: 190000,
          advancePercentage: 50,
          advanceAmount: 95000,
          balanceAmount: 95000,
          status: "pagado-completo",
          description: "Pago trabajo cocina",
          amount: 95000,
        },
      ],
      quoteHistory: [
        {
          id: "qh2",
          date: "2026-02-01",
          projectId: "p1",
          projectName: "Casa Moreno",
          category: "Mano de obra",
          item: "Demolicion y estructura",
          costProvider: 190000,
          priceClient: 266000,
          ganancia: 76000,
        },
      ],
      documents: [],
      projectIds: ["p1"],
    },
    {
      id: "pr4",
      name: "Textileria Recoleta",
      category: "Decoración",
      subcategory: "Cortinas",
      zone: "Recoleta",
      phone: "011-4811-3344",
      email: "contacto@textileriarec.com",
      contact: "Ana García",
      advancePercent: 30,
      notes: "Amplio catálogo, buenos precios",
      payments: [],
      quoteHistory: [
        {
          id: "qh3",
          date: "2026-03-02",
          projectId: "p2",
          projectName: "Depto Vidal",
          category: "Decoración",
          item: "Sillon 3 cuerpos lino",
          costProvider: 580000,
          priceClient: 928000,
          ganancia: 348000,
        },
      ],
      documents: [],
      projectIds: ["p2"],
    },
  ],
  accounts: [
    {
      id: "ac1",
      name: "Caja chica",
      balance: 15000,
      color: "#5F5A46",
    },
    {
      id: "ac2",
      name: "Cuenta banco",
      balance: 842000,
      color: "#2A4A6A",
    },
  ],
  accountMovements: [
    {
      id: "am1",
      accountId: "ac2",
      date: "2026-03-01",
      description: "Cobro cliente Moreno",
      amount: 560000,
      type: "ingreso",
      category: "Proyecto",
    },
    {
      id: "am2",
      accountId: "ac1",
      date: "2026-03-05",
      description: "Cafe reunion",
      amount: 3500,
      type: "egreso",
      category: "Varios",
    },
  ],
  tasks: [
    {
      id: "t1",
      title: "Revisar planos bano PB",
      projectId: "p1",
      dueDate: "2026-03-15",
      priority: "alta",
      status: "pendiente",
      assignee: "Paula",
    },
    {
      id: "t2",
      title: "Cotizar ceramicos faltantes",
      projectId: "p1",
      dueDate: "2026-03-18",
      priority: "media",
      status: "en-curso",
      assignee: "Cami",
    },
    {
      id: "t3",
      title: "Entrega moodboard Vidal",
      projectId: "p2",
      dueDate: "2026-03-14",
      priority: "alta",
      status: "pendiente",
      assignee: "Paula",
    },
  ],
  personalFinance: {
    paula: {
      fixedExpenses: [
        { id: "pf1", description: "Alquiler", amount: 180000, category: "Vivienda", active: true },
        { id: "pf2", description: "Expensas", amount: 25000, category: "Vivienda", active: true },
        { id: "pf3", description: "Seguro medico", amount: 42000, category: "Salud", active: true },
        { id: "pf4", description: "Netflix", amount: 4500, category: "Servicios", active: true },
      ],
      variableExpenses: [
        { id: "pv1", date: "2026-03-05", description: "Supermercado", amount: 32000, category: "Alimentacion" },
        { id: "pv2", date: "2026-03-08", description: "Nafta", amount: 18000, category: "Transporte" },
      ],
      nitiaIncome: [
        {
          id: "pi1",
          date: "2026-03-01",
          description: "Distribucion Nitia marzo",
          amount: 280000,
          note: "50% cobrado proyecto Moreno",
        },
      ],
    },
    cami: {
      fixedExpenses: [
        { id: "cf1", description: "Hipoteca", amount: 210000, category: "Vivienda", active: true },
        { id: "cf2", description: "Seguro medico", amount: 38000, category: "Salud", active: true },
        { id: "cf3", description: "Spotify", amount: 2800, category: "Servicios", active: true },
      ],
      variableExpenses: [
        { id: "cv1", date: "2026-03-06", description: "Supermercado", amount: 28000, category: "Alimentacion" },
        { id: "cv2", date: "2026-03-09", description: "Ropa", amount: 45000, category: "Personal" },
      ],
      nitiaIncome: [
        {
          id: "ci1",
          date: "2026-03-01",
          description: "Distribucion Nitia marzo",
          amount: 280000,
          note: "50% cobrado proyecto Moreno",
        },
      ],
    },
  },
  nitiaFixedCosts: [
    { id: "nf1", description: "Sueldo empleada", amount: 250000, category: "Personal", active: true },
    { id: "nf2", description: "Adobe Creative Cloud", amount: 28000, category: "Software", active: true },
    { id: "nf3", description: "AutoCAD LT", amount: 45000, category: "Software", active: true },
    { id: "nf4", description: "Dominio nitiaestudio.com", amount: 3500, category: "Web", active: true },
    { id: "nf5", description: "Hosting Vercel", amount: 8000, category: "Web", active: true },
    { id: "nf6", description: "Telefono oficina", amount: 12000, category: "Servicios", active: true },
  ],
  globalMovements: [
    {
      id: "gm1",
      date: "2026-01-20",
      description: "Sena 50% honorarios",
      amount: 560000,
      type: "ingreso",
      category: "Honorarios",
      projectId: "p1",
      providerId: null,
      accountId: "ac2",
      quoteId: null,
    },
    {
      id: "gm2",
      date: "2026-02-05",
      description: "Pago Carpinteria Lopez",
      amount: 95000,
      type: "egreso",
      category: "Mano de obra",
      projectId: "p1",
      providerId: "pr3",
      accountId: "ac2",
      quoteId: null,
    },
    {
      id: "gm3",
      date: "2026-02-18",
      description: "Anticipo corralon",
      amount: 160000,
      type: "egreso",
      category: "Materiales",
      projectId: "p1",
      providerId: "pr1",
      accountId: "ac2",
      quoteId: null,
    },
  ],
  quoteComparisons: [
    {
      id: "qc1",
      projectId: "p1",
      date: "2026-03-01",
      category: "Mueble TV",
      item: "Mueble TV roble 180cm",
      providerId: "pr4",
      providerName: "Muebles Palermo",
      cost: 420000,
      priceX14: 588000,
      priceX16: 672000,
      gananciaX14: 168000,
      gananciaX16: 252000,
      selected: false,
    },
    {
      id: "qc2",
      projectId: "p1",
      date: "2026-03-01",
      category: "Mueble TV",
      item: "Mueble TV roble 180cm",
      providerId: "pr3",
      providerName: "Fabrica Oeste",
      cost: 240000,
      priceX14: 336000,
      priceX16: 384000,
      gananciaX14: 96000,
      gananciaX16: 144000,
      selected: true,
    },
    {
      id: "qc3",
      projectId: "p1",
      date: "2026-03-02",
      category: "Sillon Living",
      item: "Sillon 3 cuerpos lino",
      providerId: "pr4",
      providerName: "Textileria Recoleta",
      cost: 580000,
      priceX14: 812000,
      priceX16: 928000,
      gananciaX14: 232000,
      gananciaX16: 348000,
      selected: false,
    },
  ],
  partnerCount: 2,
}
